---
blank_issues_enabled: false
contact_links:
  - name: Feature Request
    url: https://github.com/apache/superset/discussions/new?category=ideas
    about: Propose a feature request to the Superset community
