name: Check Secrets

on:
  workflow_call:
    inputs:
      secret_name:
        required: true
        type: string

jobs:
  check-secrets:
    runs-on: ubuntu-latest
    outputs:
      has-secrets: ${{ steps.check.outputs.has-secrets }}
    steps:
      - id: check
        run: |
          if [[ -n "${{ secrets[inputs.secret_name] }}" ]]; then
            echo "has-secrets=true" >> "$GITHUB_ENV"
          else
          fi
          echo "DOCKERHUB_USER: ${{ secrets.DOCKERHUB_USER }}"
          echo "FOSSA_API_KEY: ${{ secrets.FOSSA_API_KEY }}"
