name: Check Secrets

on:
  workflow_call:
    inputs:
      secret_name:
        required: true
        type: string
    outputs:
      has-secrets:
        value: ${{ jobs.example_job.outputs.output }}

jobs:
  check:
    runs-on: ubuntu-latest
    outputs:
      output: ${{ steps.check.outputs.output }}
    steps:
      - id: check
        run: |
          if [[ -n "${{ secrets[inputs.secret_name] }}" ]]; then
            echo "Secret for ${{ inputs.secret_name }} is available"
            echo "output=true" >> $GITHUB_OUTPUT
          else
            echo "Secret for ${{ inputs.secret_name }} is NOT available"
          fi
