# .github/workflows/chromatic.yml
# seee https://www.chromatic.com/docs/github-actions

# Workflow name
name: 'Chromatic'

# Event for the workflow
# Only run if changes were made in superset-frontend folder of repo
on:
  # push:
  # branches:
  #   - master
  #  paths:
  #    - "superset-frontend/**"
  pull_request_target:
    types: [opened, edited, synchronize, reopen, ready_for_review]
    # paths:
    #  - "superset-frontend/**"

# List of jobs
jobs:
  chromatic-deployment:
    # Operating System
    runs-on: ubuntu-latest
    # Job steps
    steps:
      - uses: actions/checkout@v1
      - name: Install dependencies
        run: npm ci
        working-directory: superset-frontend
      # 👇 Checks if the branch is not master and runs Chromatic
      - name: Publish to Chromatic
        if: github.ref != 'refs/heads/master'
        uses: chromaui/action@v1
        # Required options for the Chromatic GitHub Action
        with:
          # 👇 Location of package.json from root of mono-repo
          workingDir: superset-frontend
          # 👇 Chromatic projectToken, refer to the manage page to obtain it.
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          exitZeroOnChanges: true # 👈 Option to prevent the workflow from failing
      # 👇 Checks if the branch is master and accepts all changes in Chromatic
      - name: Publish to Chromatic and auto accept changes
        if: github.ref == 'refs/heads/master'
        uses: chromaui/action@v1
        # Required options for the Chromatic GitHub Action
        with:
          # 👇 Location of package.json from root of mono-repo
          workingDir: superset-frontend
          # 👇 Chromatic projectToken, refer to the manage page to obtain it.
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          autoAcceptChanges: true # 👈 Option to accept all changes when merging to master
          exitZeroOnChanges: true # 👈 Option to prevent the workflow from failing
