name: Generate Technical Debt Metrics

on:
  push

jobs:

  render-debt-metrics:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Generate json
      uses: actions/setup-node@v3
      with:
        node-version: 16
      run: run: npm run lint-stats

    - name: Commit and push changes
        uses: devops-infra/action-commit-push@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          commit_message: AUTOMATED - committting JSON tech debt report