name: Docs

on:
  push:
    paths:
      - "docs/**"
    branches:
      - 'master'
  pull_request:
    paths:
      - "docs/**"
    types: [synchronize, opened, reopened, ready_for_review]

jobs:
  check-secrets:
    uses: ./.github/workflows/check-secrets.yml
    with:
      secret_name: 'SUPERSET_SITE_BUILD'
    secrets: inherit
  build-deploy:
    needs: check-secrets
      #if: needs.check-secrets.outputs.hassecret == 'true'
    name: Build & Deploy
    runs-on: ubuntu-20.04
    defaults:
      run:
        working-directory: docs
    steps:
      - name: yarn install
        run: |
          echo ${{needs.check-secrets.outputs.hassecret }}
