name: Docs

on:
  push:
    paths:
      - "docs/**"
  pull_request:
    paths:
      - "docs/**"

jobs:
  build-deploy:
    name: Build & Deploy
    runs-on: ubuntu-20.04
    steps:
      - name: "Checkout ${{ github.ref }} ( ${{ github.sha }} )"
        uses: actions/checkout@v2
        with:
          persist-credentials: false
          submodules: recursive
      - name: npm install
        working-directory: ./docs
        run: |
          npm install
      - name: lint
        working-directory: ./docs
        run: |
          npm run lint
      - name: gatsby build
        working-directory: ./docs
        run: |
          npm run build
